const score = 400;
console.log(score);
const balance = new Number(100);
console.log(balance);
console.log(balance.toString().length);
console.log(balance.toFixed(1));
const otherNumber = 123.456;
console.log(otherNumber.toPrecision(4));

const hundred = 100000;
console.log(hundred.toLocaleString("en-IN"));
console.log(Number.MAX_VALUE);
console.log(Number.MIN_VALUE);
console.log(Number.POSITIVE_INFINITY);
console.log(Number.isSafeInteger);
console.log( `-----------------------------------Math----------------------------`);
console.log(Math);
console.log(Math.abs(-4));
console.log(Math.round(4.6));
console.log(Math.ceil(4.3));
console.log(Math.floor(4.3));
console.log(Math.random());
console.log(Math.random() * 10 + 1);
console.log(Math.max(1,2,3,4,5));
console.log(Math.min(1,2,3,4,5));
console.log(Math.pow(2,3));
console.log(Math.sqrt(9));
console.log(Math.cbrt(8));
console.log(Math.E);
console.log(Math.LN10);
console.log(Math.LN2);
console.log(Math.log(10));
console.log(Math.log2(10));

